# Shadowrocket Ultimate Stability Config
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = 8.8.8.8, 1.1.1.1, system
dns-direct-system = true
dns-fallback-system = false
dns-direct-fallback = false
always-real-ip = *.apple.com, *.apple-dns.net, *.icloud.com, *.live.com, *.microsoft.com
keep-alive-interval = 15
tcp-fast-open = true
tls-session-ticket-resumption = true
udp-policy-not-supported-behaviour = REJECT
network-changed-process = 1
disconnect-on-policy-change = false
ipv6 = false
prefer-ipv6 = false

[Rule]
# 1. Blocks & Rejections
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ads.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt,REJECT

# 2. Local & Iranian Direct Traffic
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/private.txt,DIRECT,no-resolve
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/apps.txt,DIRECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt,DIRECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.txt,DIRECT
RULE-SET,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt,DIRECT
GEOIP,IR,DIRECT

# 3. Fallback
FINAL,PROXY

[Host]
localhost = 127.0.0.1
